version: "2"
services:
  app:
    container_name: linebot
    restart: on-failure
    image: linebot
    ports:
      - "8000:8000"
    working_dir: /app
  db:
    container_name: mongodb
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017