version: "2"
services:
  app:
    container_name: linebot
    restart: on-failure
    image: linebot
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 27017:27017
  